name: Code Analysis - CodeQL

on:
  pull_request:
    branches:
      - main
      - develop
      - 'feature/**'

jobs:
  code-analysis-codeql:
    name: Code Analysis - CodeQL
    runs-on: ubuntu-latest

    permissions:
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language:
          - python

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
