name: Type Enforcement - mypy

on:
  pull_request:
    branches:
      - main
      - develop
      - 'feature/**'

permissions:
  contents: read

jobs:
  type-enforcement-mypy:
    name: Type Enforcement - mypy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
          pip install mypy

      - name: Lint with mypy
        run: mypy --pretty --strict .
