name: Code Linting - pylint

on:
  pull_request:
    branches:
      - main
      - develop
      - 'feature/**'

permissions:
  contents: read

jobs:
  linter-pylint:
    name: Code Linting - pylint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
          pip install pylint

      - name: Lint with pylint
        run: pylint --rcfile=.pylintrc --recursive y .
